name: Build

on: push
env:
  NODE_VERSION: "16.13.1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          npm install -g ajv-cli ajv-formats
          chmod +x ./test.sh
          bash ./test.sh
